[build]
  base = "RationFlow/RationFlow-main"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/gesture"
  to = "/gesture.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
